"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Href_1 = require("src/components/Href");
var Pdf_1 = require("src/components/Pdf");
var Exp = function () {
    return (React.createElement(React.Fragment, null,
        React.createElement("div", { className: 'tertiary' },
            React.createElement("h3", { id: 'exp' }, "Experience"),
            React.createElement("p", { className: 'title' },
                "Associate IT Systems Engineer - ",
                React.createElement("a", { href: "https://www.floridablue.com/" }, "Florida Blue")),
            React.createElement("p", { className: 'mt_0' }, "2022 - Present"),
            React.createElement("p", { className: 'margins_small' }, "Designing and constructing, high-availability OpenShift clusters along with working closely with developers in the CI/CD process. Built automation programs using the Go language for creating OpenShift objects automatically, reducing workload and time to production for critical components."),
            React.createElement("p", null,
                "Tech Lead and ",
                React.createElement(Href_1.default, { link: "https://www.figma.com/", name: "Figma" }),
                " designer for a fullstack application that utilizes ",
                React.createElement(Href_1.default, { link: "https://react.dev/", name: "React" }),
                ", ",
                React.createElement(Href_1.default, { link: "https://fastapi.tiangolo.com/", name: "FastAPI" }),
                ", ",
                React.createElement(Href_1.default, { link: "https://www.microsoft.com/en-us/sql-server/sql-server-2022", name: "SQL Server" }),
                ", other technologies for tracking yearly enterprise expenses. "),
            React.createElement("p", { className: 'skills' },
                "Skills: ",
                React.createElement(Href_1.default, { link: "https://www.redhat.com/en/technologies/cloud-computing/openshift", name: "OpenShift" }),
                ", Red Hat Products, ",
                React.createElement(Href_1.default, { link: "https://nodejs.org/en/blog/announcements/v20-release-announce", name: "Node" }),
                ", ",
                React.createElement(Href_1.default, { link: "https://react.dev/", name: "React" }),
                ", ",
                React.createElement(Href_1.default, { link: "https://fastapi.tiangolo.com/", name: "FastAPI" }),
                " "),
            React.createElement("p", { className: 'title' },
                "Network Administrator - ",
                React.createElement("a", { href: "https://www.airforce.com/ways-to-serve/air-national-guard" }, "Air National Guard")),
            React.createElement("p", { className: 'mt_0' }, "2018 - 2022"),
            React.createElement("p", { className: 'margins_small' }, "Responsible for planning, deploying, configuring, and maintaining the network infrastructure that supports operational needs in temporary, dynamic, and often austere environments"),
            React.createElement("p", null, "Team Lead for several exercises, coordinating drills with leadership and ensuring mission success."),
            React.createElement("p", { className: 'skills' }, "Skills: Cisco switches, Cisco Routing, Troubleshooting, Leadership"),
            React.createElement("a", { className: 'resume_link', href: "src/assets/Austin_Leverett.pdf" },
                React.createElement("p", { className: 'resume_link' },
                    "View Full Resume ",
                    React.createElement(Pdf_1.default, null))))));
};
exports.default = Exp;
